<?php


namespace kahra\dev\src\view\page;

class KonamiPage extends Page {

    public function __construct() {
        parent::__construct("^^vv<><>bastart", "konami");
    }

    function renderBody() { ?>
        o.O This is a test page. HELLO!
        <br/><br/>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet dui ac purus tempus placerat. Vestibulum dignissim nulla felis, ultricies tristique elit congue semper. Aliquam consectetur mollis lectus quis efficitur. Integer vestibulum, nisl quis auctor sollicitudin, leo dolor tincidunt tellus, ac egestas eros arcu luctus tortor. Sed consectetur condimentum augue nec auctor. Nullam in porta nulla. Donec quis massa eleifend, semper nunc at, pretium augue. Sed facilisis eros consectetur nibh egestas efficitur. Praesent placerat nisi ac dui pulvinar, a consequat ligula lobortis. Nam laoreet pulvinar neque quis auctor.
        <br/><br/>
        Nam sodales neque ac risus molestie luctus at ut magna. Nunc sit amet libero sed velit hendrerit vehicula. Vivamus metus nisl, maximus ut consequat ut, molestie quis justo. Suspendisse id ante nec massa mattis auctor. Aenean elementum tellus vitae urna sollicitudin bibendum. Cras non laoreet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ullamcorper dolor lacus, ut semper felis convallis nec. In vulputate eu erat eget porta. Phasellus nec placerat sem. Sed congue sem est, a vestibulum metus consectetur et. Nullam posuere quam arcu, nec luctus augue scelerisque id. Suspendisse potenti. Nam quis aliquam ante.
        <br/><br/>
        Pellentesque et tempor erat. Ut sagittis et quam eu feugiat. In hac habitasse platea dictumst. Donec tempor arcu vel tortor sagittis, quis faucibus augue lacinia. In dignissim, diam id venenatis sollicitudin, felis justo dignissim nunc, eu dignissim nunc nunc eget arcu. Vestibulum ultricies justo sit amet metus vulputate, vel placerat augue fermentum. Quisque vehicula lacus in nulla accumsan euismod. Integer cursus lectus non orci luctus scelerisque. Curabitur laoreet ex at efficitur fringilla. Suspendisse quam lectus, sollicitudin at orci quis, congue varius orci. Donec laoreet, leo in dapibus porta, urna magna volutpat arcu, nec hendrerit risus sapien quis justo. Suspendisse potenti. Donec posuere, ligula quis condimentum aliquam, nunc metus pretium libero, et mattis magna ligula vel ante. Maecenas semper orci nisl, molestie imperdiet velit mollis vel. Nunc ornare ac felis sit amet consequat. Vestibulum at malesuada turpis.
        <br/><br/>
        Vestibulum a sagittis elit. Nulla vel nulla vel quam placerat facilisis. Nunc massa nisl, sodales ut lacus vitae, tempus sagittis tortor. Nullam dictum non velit quis aliquet. Proin ultrices quam ultrices est ultricies consequat. Proin sit amet sem lacus. Maecenas molestie odio sit amet felis fermentum, ac blandit ante posuere. Maecenas sagittis neque libero, at lobortis quam volutpat et. Phasellus maximus faucibus ligula ac rhoncus. Vestibulum rutrum velit ut velit sollicitudin, eget molestie ex tincidunt.
        <br/><br/>
        In sed congue quam. Aliquam molestie pretium lorem, et aliquam leo fringilla eu. Vestibulum euismod neque est, sed placerat velit viverra a. Vivamus facilisis commodo ligula, non euismod erat laoreet a. Duis aliquam aliquam augue, quis volutpat enim dignissim nec. Maecenas placerat aliquam tortor ac tempor. Nulla tincidunt eros eu justo fermentum, ac bibendum risus pulvinar. Vivamus leo augue, interdum non laoreet sit amet, sollicitudin non est. Pellentesque luctus tortor id semper tempus. Praesent vel nibh at nunc molestie luctus nec tempus est.
        <br/><br/>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet dui ac purus tempus placerat. Vestibulum dignissim nulla felis, ultricies tristique elit congue semper. Aliquam consectetur mollis lectus quis efficitur. Integer vestibulum, nisl quis auctor sollicitudin, leo dolor tincidunt tellus, ac egestas eros arcu luctus tortor. Sed consectetur condimentum augue nec auctor. Nullam in porta nulla. Donec quis massa eleifend, semper nunc at, pretium augue. Sed facilisis eros consectetur nibh egestas efficitur. Praesent placerat nisi ac dui pulvinar, a consequat ligula lobortis. Nam laoreet pulvinar neque quis auctor.
        <br/><br/>
        Nam sodales neque ac risus molestie luctus at ut magna. Nunc sit amet libero sed velit hendrerit vehicula. Vivamus metus nisl, maximus ut consequat ut, molestie quis justo. Suspendisse id ante nec massa mattis auctor. Aenean elementum tellus vitae urna sollicitudin bibendum. Cras non laoreet orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris ullamcorper dolor lacus, ut semper felis convallis nec. In vulputate eu erat eget porta. Phasellus nec placerat sem. Sed congue sem est, a vestibulum metus consectetur et. Nullam posuere quam arcu, nec luctus augue scelerisque id. Suspendisse potenti. Nam quis aliquam ante.
        <br/><br/>
        Pellentesque et tempor erat. Ut sagittis et quam eu feugiat. In hac habitasse platea dictumst. Donec tempor arcu vel tortor sagittis, quis faucibus augue lacinia. In dignissim, diam id venenatis sollicitudin, felis justo dignissim nunc, eu dignissim nunc nunc eget arcu. Vestibulum ultricies justo sit amet metus vulputate, vel placerat augue fermentum. Quisque vehicula lacus in nulla accumsan euismod. Integer cursus lectus non orci luctus scelerisque. Curabitur laoreet ex at efficitur fringilla. Suspendisse quam lectus, sollicitudin at orci quis, congue varius orci. Donec laoreet, leo in dapibus porta, urna magna volutpat arcu, nec hendrerit risus sapien quis justo. Suspendisse potenti. Donec posuere, ligula quis condimentum aliquam, nunc metus pretium libero, et mattis magna ligula vel ante. Maecenas semper orci nisl, molestie imperdiet velit mollis vel. Nunc ornare ac felis sit amet consequat. Vestibulum at malesuada turpis.
        <br/><br/>
        Vestibulum a sagittis elit. Nulla vel nulla vel quam placerat facilisis. Nunc massa nisl, sodales ut lacus vitae, tempus sagittis tortor. Nullam dictum non velit quis aliquet. Proin ultrices quam ultrices est ultricies consequat. Proin sit amet sem lacus. Maecenas molestie odio sit amet felis fermentum, ac blandit ante posuere. Maecenas sagittis neque libero, at lobortis quam volutpat et. Phasellus maximus faucibus ligula ac rhoncus. Vestibulum rutrum velit ut velit sollicitudin, eget molestie ex tincidunt.
        <br/><br/>
        In sed congue quam. Aliquam molestie pretium lorem, et aliquam leo fringilla eu. Vestibulum euismod neque est, sed placerat velit viverra a. Vivamus facilisis commodo ligula, non euismod erat laoreet a. Duis aliquam aliquam augue, quis volutpat enim dignissim nec. Maecenas placerat aliquam tortor ac tempor. Nulla tincidunt eros eu justo fermentum, ac bibendum risus pulvinar. Vivamus leo augue, interdum non laoreet sit amet, sollicitudin non est. Pellentesque luctus tortor id semper tempus. Praesent vel nibh at nunc molestie luctus nec tempus est.
    <?php }
}